language: php

php:
  - '7.2'
  - '7.4'
  - '8.0'
  - '8.1'

env:
  global:
    - CI: 'true'
    - TEST_OUTPUT_STYLE: 'pretty'
    - PHPCS_REPORT_STYLE: 'full'
    - COMPOSER_OPTIONS: '--optimize-autoloader'
  jobs:
    - SYMFONY_VERSION: '^4.4'
    - SYMFONY_VERSION: '^5.4'

jobs:
  fast_finish: true

before_install:
  # remove xdebug to speed up build
  - phpenv config-rm xdebug.ini || true

install:
  - composer require symfony/http-foundation:$SYMFONY_VERSION symfony/http-kernel:$SYMFONY_VERSION symfony/config:$SYMFONY_VERSION symfony/dependency-injection:$SYMFONY_VERSION symfony/event-dispatcher:$SYMFONY_VERSION symfony/routing:$SYMFONY_VERSION
  - make build
script:
  - make test-technical
  - make test-functional

cache:
  directories:
    - $HOME/.composer
    - vendor

branches:
  except:
  - /.*\-dev$/
  - /^dev-.*$/
  - /.*\-patch(\-\d+)?$/
