services:
  _defaults:
      public: true

  json_rpc_http_server.endpoint:
    class: Yoanm\SymfonyJsonRpcHttpServer\Endpoint\JsonRpcHttpEndpoint
    arguments:
      - '@json_rpc_server_sdk.infra.endpoint'

  json_rpc_http_server.dispatcher.server:
    class: Yoanm\SymfonyJsonRpcHttpServer\Dispatcher\SymfonyJsonRpcServerDispatcher
    arguments:
      - '@event_dispatcher'

  json_rpc_http_server.method_resolver:
    class: Yoanm\SymfonyJsonRpcHttpServer\Resolver\MethodResolver
    arguments:
      - '@json_rpc_http_server.service_subscriber.method_resolver'
